### ISSUE TITLE
Index OS bricked my playdate :(

### ISSUE THREAD

**Issue by Nanobot567** [scratchminer/Index-OS#3] opened 2023-05-06 18:49 UTC
I opened an app called "Pocket Planner". After exiting, my playdate threw an error that said something about a missing displayImages function. I then tried to boot into recovery firmware. I did this and tried to upgrade to 1.13.7. Now it's stuck flashing between applying system update and the playdate screen. I was on 1.13.7. Guess this is what I get haha

**Comment by scratchminer** [comment] 2023-05-06 18:57
I have the same issue with recovery firmware sometimes. Can you check the serial console in the Simulator? (Another thing to try is hitting the reset button in the crank dock, which solved it for me a couple times.)

**Comment by Nanobot567** [comment] 2023-05-06 18:58
Nothing in the serial console. It doesn't detect the playdate at all. I also already tried the reset button a couple times.

**Comment by scratchminer** [comment] 2023-05-06 18:59
> something about a missing displayImages function

Do you have the exact error message or stack trace? It would be helpful so I can track down the error.

**Comment by Nanobot567** [comment] 2023-05-06 18:59
No, I didn't think to take a picture. In hindsight I probably should have though.

**Comment by scratchminer** [comment] 2023-05-06 19:01
You have the unlock key for your Playdate right? If so you can boot into its system disk and run Disk Utility (Mac) or `chkdsk /f /r` (Windows). I have a hunch that you've got isolated data on the system disk causing it not to update properly.

**Comment by Nanobot567** [comment] 2023-05-06 19:04
That's the thing, on my computer it's not detected at all, the serial port doesn't exist.

**Comment by scratchminer** [comment] 2023-05-06 19:07
Interesting. On my computer when that happens, the Playdate ends up connecting and disconnecting repatedly from the serial interface as it reboots. If you have a Unix-compatible computer try installing `picocom` and trying the serial interface until it connects, I don't know about Windows though

**Comment by scratchminer** [comment] 2023-05-06 19:09
Also, a bootloader test to perform: Triple-clicking the reset button should boot your Playdate into the recovery disk. If it doesn't then your bootloader isn't working.

**Comment by scratchminer** [comment] 2023-05-06 19:13
I'll try to reproduce the update conditions on my Playdate, we'll see if it works

**Comment by Nanobot567** [comment] 2023-05-06 19:17
Alright, that worked! I now see a drive called BOOTSY on my computer with nothing in it, except for version.txt.

**Comment by scratchminer** [comment] 2023-05-06 19:19
All right, then you've got a working bootloader.
(Incidentally, are you on Mac or Windows?)

**Comment by Nanobot567** [comment] 2023-05-06 19:20
I am on Windows.

**Comment by scratchminer** [comment] 2023-05-06 19:25
Oh -- that might be the reason the serial port doesn't connect. I guess Windows handles serial comms differently than Unix. I use a Mac normally, and my guess is that you have a filesystem error on your Playdate, causing it to reboot constantly. It was fixed for me by booting to the system disk and running Disk Utility.

**Comment by scratchminer** [comment] 2023-05-06 19:26
Can you try booting to recovery firmware from the crash loop? I'm not sure if that'll help anything, but it's worth a shot.

**Comment by Nanobot567** [comment] 2023-05-06 19:27
I tried doing that earlier, it didn't work.

**Comment by Nanobot567** [comment] 2023-05-06 19:32
Ok somehow pressing the reset button a million times got me into the DATA segment, the filesystem is readable by windows though. I guess that makes it a problem with the SYSTEM partition?

**Comment by scratchminer** [comment] 2023-05-06 19:35
Yep! That's why I had you try to boot into BERNARD.

**Comment by Nanobot567** [comment] 2023-05-06 19:36
Oh, right, duh, sorry haha.

Also I have the traceback you were asking for earlier now:

```
2023/05/06 13:27:05
/System/Launcher.pdx
views/cardView.lua:240: method 'loadCardImages' is not callable (a nil value)
stack traceback:
	views/cardView.lua:240: in upvalue 'loadAll'
	views/cardView.lua:1719: in method 'draw'
	main.lua:443: in function <main.lua:440>
```

**Comment by scratchminer** [comment] 2023-05-06 19:39
That bug will be fixed in the next release.

How are you connecting to the Playdate via serial? Are you using your `psi` tool?

**Comment by Nanobot567** [comment] 2023-05-06 19:41
Yeah I tried using that first, then I tried using picocom through WSL. I'm not entirely sure what my playdate's serial number is, but I just used the digits after the dash on the playdate website.

**Comment by scratchminer** [comment] 2023-05-06 19:42
Your serial is printed inside the crank dock, and it should start with `PDU1-Y`.

**Comment by Nanobot567** [comment] 2023-05-06 19:49
Just tried it, didn't work.

**Comment by scratchminer** [comment] 2023-05-06 19:57
The serial command should reach the Playdate while it is trying to copy, so there's around half a second of time before it reboots again. Make sure you don't try to connect too early, while the bootloader is still going, and paste the `unlock` and `sysdisk` commands in quickly enough so the Playdate receives them before it reboots.

**Comment by Nanobot567** [comment] 2023-05-06 20:15
I tried sending the command when you said, it still didn't work. The port is supposed to be /dev/cu.usbmodemPD(serial), correct?

**Comment by scratchminer** [comment] 2023-05-06 20:35
`dev/cu.usbmodemPDU1-YXXXXX` is the port.

**Comment by Nanobot567** [comment] 2023-05-06 20:40
Dang, that didn't work either. I can factory reset if that's possible, I backed everything up from the data partition

**Comment by scratchminer** [comment] 2023-05-06 21:22
I suppose you could try that, I don't know what else to do at this point.
I'm sorry I couldn't help more.

**Comment by Nanobot567** [comment] 2023-05-06 22:15
How would I go about factory resetting from the state that it's in? And if that doesn't work, should I email Panic?

Also, don't be sorry! You've helped a ton. Thanks :)

**Comment by scratchminer** [comment] 2023-05-06 23:08
I'd say reach out to Dave on the forums, because since the bootloader works he can DM you the firmware build. I've done all I can do here, so I'm going to close the issue.

**Closed as completed** 2023-05-06 23:08 UTC
Labels: bug

**Comment by Nanobot567** [comment] 2023-05-06 23:10
Alright, thanks again! If I can't resolve the issue I guess I took one for the team 😅
